In [1]:
!pip3 install numpy

In [2]:
import numpy as np


### we are giving alias to numpy as np now we can use it in place of numpy

In [3]:
arr = np.array([[1,2,3],[4,2,5]])

In [4]:
type(arr)

numpy.ndarray

#### advantage of numpy array for python array is

In [5]:
arr.ndim

2

In [6]:
arr.shape#no of rows and number of columns

(2, 3)

In [7]:
arr.size# total number of elements


6

In [8]:
arr.dtype

dtype('int32')

In [9]:
# different ways to create an array
#1.array created using passed list
a = np.array([[1,2,3],[4,5,6]],dtype = 'float')
#2.array created using tuple
b = np.arry(((1,2,3),(4,5,6)))


AttributeError: module 'numpy' has no attribute 'arry'

In [10]:
#1.array created using passed list
a = np.array([[1,2,3],[4,5,6]],dtype = 'float')

In [11]:
print(a)

[[1. 2. 3.]
 [4. 5. 6.]]


In [12]:
#2.array created using tuple
b = np.arry(((1,2,3),(4,5,6)))


AttributeError: module 'numpy' has no attribute 'arry'

In [13]:
#2.array created using tuple
b = np.arry((1,2,3),(4,5,6))
print(b)


AttributeError: module 'numpy' has no attribute 'arry'

In [14]:
c = np.zeros((3,4))
print(c)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [15]:
d = np.ones((4,5))
print(d)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [16]:
e = np.eye(3)#identity matrix is a square matrix
print(e)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [17]:
np.arrange?


Object `np.arrange` not found.


In [18]:
np.arange?

In [19]:
f = np.arange(3,50,5)# 5 is a step size
print(f)

[ 3  8 13 18 23 28 33 38 43 48]


In [20]:
p = np.linspace(0,5,10)# 10 numbers between 0 to 5
print(p)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [21]:
ar = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)

[[1 2 3]
 [4 2 5]]


In [22]:
print(ar)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [23]:
newar = ar.reshape(2,2,3)
print(newar)

ValueError: cannot reshape array of size 9 into shape (2,2,3)

In [26]:
newarr = ar.reshape(1,9)
print(newarr)

[[1 2 3 4 5 6 7 8 9]]


In [28]:
A = np.array([1,2,3,4])

In [29]:
A+1

array([2, 3, 4, 5])

In [30]:
A-2

array([-1,  0,  1,  2])