# Numpy Exercise

#### 1. Import the numpy package under the name as np  

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration 

In [2]:
import numpy
print(numpy.__version__)

1.20.1


#### 3. Create a null vector of size 10

In [3]:
x = np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array

In [4]:
print(x.size)

10


#### 5.  How to get the documentation of the numpy add function from the command line? 

In [10]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1

In [6]:
p = np.zeros(10)
p[5] = 1
print(p)

[0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]


#### 8.  Reverse a vector (first element becomes last)

In [7]:
a = np.array([1,2,3,4,5])
print(a[::-1])

[5 4 3 2 1]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8

In [8]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\]

In [ ]:
c = np.array([1,2,0,0,4,0])
print()

#### 11. Create a 3x3 identity matrix

In [9]:
id= np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values

In [11]:
t = np.random.uniform((3,3,3))
print(t)

[1.5399097  2.06546088 1.39744773]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values

In [12]:
z = np.random.random((10,10))
a = z.min()
b = z.max()
print(a,b)

0.0018223485601401856 0.9935814482887242


#### 14. Create a random vector of size 30 and find the mean value

In [13]:
k = np.random.random((30))
a = k.mean()
print(a)

0.5462289648340184


#### 15. Create a 2d array with 1 on the border and 0 inside

In [24]:
n = np.zeros((10,10))
n[1:-1,1:-1] =1
print(n)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 16. How to add a border (filled with 0's) around an existing array?

In [23]:
p = np.ones((10,10))
p[0:-1,0:-1]=0
print(p)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 17. What is the result of the following expression?

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

#nan = not a number
# inf = positive infinity

In [14]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)

nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal

In [29]:
ans = np.diag([1,2,3,4],-1)
ans

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern

In [27]:
k= np.zeros ((8,8), dtype=int)
k[1::2, ::2]= 1
k[::2,1::2] = 1
print(k)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [28]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)
